### ISSUE TITLE
 Error: Command failed: heroku container:login

### ISSUE THREAD

**Issue by LDubya** [jkrup/meteor-hero#12]
@jkrup I've been experiencing this issue for about a week now. Thought I'd be able to figure it out but haven't. Same issue whether or not I include a `prod.env` file. Any ideas?

```console
username@Macbook appRoot % meteor-hero -E prod.env
clearing build folder
Building meteor app...
Building meteor app (this can take several minutes)
Node#moveTo was deprecated. Use Container#append.
Built
Unzipping meteor bundle...
Writing Dockerfile...
Creating heroku container...
Creating app... done, heroku-appname-12345
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
 ▸    Login failed with: 1

  🚨 Something happened that probably shouldn't have.

  Details:
    Error: Command failed: heroku container:login
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
 ▸    Login failed with: 1

    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at herokuLogin (/Users/username/.nvm/versions/node/v12.10.0/lib/node_modules/meteor-hero/commands/newDeploy.js:99:3)
    at newDeploy (/Users/username/.nvm/versions/node/v12.10.0/lib/node_modules/meteor-hero/commands/newDeploy.js:173:5)
    at Object.<anonymous> (/Users/username/.nvm/versions/node/v12.10.0/lib/node_modules/meteor-hero/index.js:13:5)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)

  Run meteor-hero -h to see the full help menu and list of options

  If all else fails go to https://github.com/jkrup/meteor-hero/issues and post an issue there.


```

```console
$ meteor --version       
Meteor 1.10.2

```

node version is v12.10.0, but I get the same error when I downgrade to 8.10.

**Comment by LDubya** [comment]
@jkrup 

After logging into Heroku, it looks like it's being created as a "heroku-18" stack, instead of a "container" stack. Is there a setting that needs to be set on deployment via meteor-hero to endure it's deployed using the "container" stack?

<img width="1165" alt="Screen Shot 2020-09-26 at 6 47 24 PM" src="https://user-images.githubusercontent.com/6056426/94351647-2d622d00-0029-11eb-8f25-fcbdf2c0d144.png">

**Comment by LDubya** [comment]
update: 

Tried doing `heroku stack:set container -a heroku-appname-12345`, but it led to the same issue after `meteor-hero -u`. Looks like it's just not deploying correctly to begin with.

**Comment by LDubya** [comment]
update:

This issue exists for both brand new deployments and updating pre-existing, previously functional deployments. Had an app deployed by meteor-heroku back in August. Updated it now, and am receiving the same error. Completely stumped, looks like something's wrong during deployment.

**Comment by LDubya** [comment]
Was able to get a bit further along by installing Docker Desktop. However, the deploy process hangs and never finishes. And it's still showing up as a "heroku-18" stack instead of a "container" stack.

```console
username@Macbook appRoot % meteor-hero -E prod.env
clearing build folder
Building meteor app...
Building meteor app (this can take several minutes)
Node#moveTo was deprecated. Use Container#append.
Built
Unzipping meteor bundle...
Writing Dockerfile...
Creating heroku container...
Creating app... done, heroku-appname-12345
Setting ROOT_URL, NODE, MONGO_URL and restarting heroku-appname-12345... done, v3

(HANGS HERE, NEVER FINISHES)
```

**Comment by LDubya** [comment]
@jkrup are you experiencing these issues? Any suggestions on how to fix? I haven't been able to deploy with this package for two weeks. Been deploying using other methods but would like to be able to use this again.
